### ISSUE TITLE
[suggestion] Save time by using native JSON-stringify methods for beautify/uglify content + a JavaScript variation you may add :]

### ISSUE THREAD

**Issue by ghost** [joedf/JSON_BnU#1]
There are some tricks in most languages that will allow you to use the very-optimized, native, JSON "stringify" methods instead/in additional to character-per-character processing, like you do now.

For PHP- using http://php.net/manual/en/function.json-encode.php
with  <code>JSON_PRETTY_PRINT</code> flag will give you a beautify string, w/o it you'll get the minified one (you can also add <code> JSON_UNESCAPED_UNICODE</code> and some other flags from the web-page above).

In JavaScript it is quite similar:

```js
var json = {a:1,b:2,c:[3,4,5]};
JSON.stringify(json); //uglify/min.
JSON.stringify(json,null,2); //beautify with two spaces
JSON.stringify(json,null,2).replace(/,\n /g, "\n ,").replace(/ *(,(\ +))/g,"$2,"); //beautify with two spaces and comma-first syntax.
```

I wonder if there are similar methods in AHK (the the other languages you use)?

**Comment by joedf** [comment]
You are correct, but these are simply low dependency implementations in case JSON functions are unavailable for some reason. In AHK, there is no stringify function: at least that I know of... Objects have a similar syntax but cannot be converted from or to a string.

**Comment by ghost** [comment]
>low dependency implementations

True enough.
>In AHK

I guess it make some sense to choose a solution that
can be implemented similarly in all of the languages.

**Comment by joedf** [comment]
But none the less, I do agree with you. If built-in JSON functions exist, it's better to use them. 👍
